export enum PROJECT_ACTION_TYPES {
  FETCH_PROJECT_START = 'project/FETCH_PROJECT_START',
  FETCH_PROJECT_SUCCESS = 'project/FETCH_PROJECT_SUCCESS',
  FETCH_PROJECT_FAILED = 'project/FETCH_PROJECT_FAILED',
  ADD_TASK_START = 'project/ADD_TASK_START',
  ADD_TASK_SUCCESS = 'project/ADD_TASK_SUCCESS',
  ADD_TASK_FAILED = 'project/ADD_TASK_FAILED',
  DELETE_TASK_START = 'project/DELETE_TASK_START',
  SORT_TASK_START = 'project/SORT_TASK_START',
  UPDATE_TASK_STATUS_START = 'project/UPDATE_TASK_STATUS_START'
}
