export enum PROJECT_ACTION_TYPES {
  FETCH_PROJECT_START = 'project/FETCH_PROJECT_START',
  FETCH_PROJECT_SUCCESS = 'project/FETCH_PROJECT_SUCCESS',
  FETCH_PROJECT_FAILED = 'project/FETCH_PROJECT_FAILED'
}
